import type { ArcConfig } from "@euglowlabs/arc-shared";
import { stringify as stringifyYaml } from "yaml";

/**
 * Serialize an `ArcConfig` (or a partial draft built from `arc init`
 * answers) into the YAML representation written to disk.
 *
 * Adds a one-line generated-by header so users can spot machine-written
 * configs at a glance. The header date is computed once per call from
 * the system clock; tests should pass `now` explicitly to make output
 * deterministic.
 */
export function serializeArcConfig(cfg: Partial<ArcConfig>, now: Date = new Date()): string {
  const isoDate = now.toISOString().slice(0, 10);
  const header = `# arc.config.yml — generated by \`arc init\` on ${isoDate}\n`;
  const body = stringifyYaml(cfg, { lineWidth: 100, indent: 2 });
  return `${header}${body}`;
}
